openapi: 3.0.0
info:
  title: API de Mensajes
  description: API para guardar, recuperar y eliminar mensajes en MongoDB. Soporta texto y archivos PDF.
  version: 1.0.0
servers:
  - url: https://couto.onrender.com

paths:
  /message:
    post:
      summary: Guardar un nuevo mensaje (texto o PDF)
      operationId: guardarMensaje
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                nombre:
                  type: string
                contenido:
                  type: string
                pdf:
                  type: string
                  format: binary
              required:
                - keyword
                - nombre
      responses:
        '201':
          description: Mensaje guardado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                  new_message:
                    type: object

    get:
      summary: Recuperar un mensaje por nombre
      operationId: obtenerMensaje
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
        - name: nombre
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mensaje encontrado
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Mensaje no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string

    delete:
      summary: Eliminar un mensaje por nombre
      operationId: eliminarMensaje
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
        - name: nombre
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mensaje eliminado
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
        '404':
          description: Mensaje no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string

  /messages:
    delete:
      summary: Eliminar todos los mensajes (requiere clave)
      operationId: eliminarTodos
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todos los mensajes eliminados
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
        '403':
          description: Clave incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string